apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever
  labels:
    app: retriever
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: retriever
  template:
    metadata:
      labels:
        app: retriever
    spec:
      containers:
      - name:  retriever
        image: gcr.io/프로젝트ID/ai-server:latest # GKE 레지스트리 주소
        ports:
        - containerPort: 8080 
        envFrom:
        - secretRef:
            name: swchat-secret